### ISSUE TITLE
Can't toggle dark mode on mobile

### ISSUE THREAD

**Issue by HelmicNewciv** [Mindful-Design/Lagertha#3]
While the interface will allow me to move the slider for setting light or dark mode, it won't actually change the color scheme of the web panel.

**Comment by Mindful-Design** [comment]
Hm, that is weird... I know I had issues with actually accessing the menu at all on mobile in the early days since there were hidden elements on top of it. Might be a cache issue. Thanks for reporting it, I'll look into it today! :)

**Comment by Mindful-Design** [comment]
Found the issue, I'll push the fix asap!
